### ISSUE TITLE
Error and Reboot in v.8.

### ISSUE THREAD

**Issue by syatihoko** [avito-tech/bioyino#75]
Bioyino in docker, network host

thread 'bioyino_cnt4' panicked at 'called `Option::unwrap()` on a `None` value', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/bioyino-metric-0.5.0/src/metric.rs:511:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'bioyino_cnt3' panicked at 'called `Option::unwrap()` on a `None` value', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/bioyino-metric-0.5.0/src/metric.rs:511:51

**Comment by syatihoko** [comment]
Return v0.7.1
thread 'bioyino_carbon' panicked at 'called `Option::unwrap()` on a `None` value', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/bioyino-metric-0.3.1/src/aggregate.rs:262:70

**Comment by syatihoko** [comment]
I want to understand if this is related to carbon, I suspect that haproxy standing in front of carbon affects

**Comment by Albibek** [comment]
Hi. It's most likely not related to external peers. 

Looks like the error appears due to incorrect float values received for timers(`ms`): NaN, +inf, -inf. This should be fixed on bioyino side to filter out such values, but you can work around this on your side by checking the values you are sending.

**Comment by syatihoko** [comment]
Found out the cause of the problem
